/**
 * Created by coder on 2018/3/28.
 */

export const ACTION_AUTH = {
	LOGIN:'ACTION_AUTH.LOGIN',
	LOGOUT:'ACTION_AUTH.LOGOUT',
	LOGIN_FAIL:'ACTION_AUTH.LOGIN_FAIL',
};

export const ACTION_NOTIFY = {
	CHANGE:'ACTION_NOTIFY.CHANGE',
	SET_NEWEST:'ACTION_NOTIFY.SET_NEWEST',
};
